### ISSUE TITLE
using without stylelint-scss result in a lot of "Unknown rule scss/***" warnings

### ISSUE THREAD

**Issue by randomunrandom** [prettier/stylelint-config-prettier#127]
I'm writing a project with css only and when I try to add this preset to my config, stylelint spams a lot of warnings about "Unknown rule scss/***", as seen on screenshot
![screenshot from my termninal](https://user-images.githubusercontent.com/37236863/136859155-7a57fe83-aae5-4699-b2fc-98ef2bc82809.png)
As I understand, this happens because I don't use [`stylelint-scss`](https://github.com/kristerkari/stylelint-scss) plugin, which creates this rules.
To solve this, I copied all of the rules, except for scss ones, from [`src/index.js`](https://github.com/prettier/stylelint-config-prettier/blob/65942d026278bc7be2e362a6369121f1f01b36d5/src/index.js) to my config.
I think that scss rules shouldn't be included by default and something similar to preset in [`stylelint-prettier`](https://github.com/prettier/stylelint-prettier), which would include these rules in addition to standard ones would be better, but I'm not sure how to do that.

**Comment by riddla** [comment]
This isn't fixed, as for example `scss/operator-no-newline-after` is still (or again) enabled and causing errors.

**Comment by shannonmoeller** [comment]
@riddla Are you sure you're using the latest version of stylelint-confit-prettier, that it's the last entry in your eslint config's extends array, and that you haven't added any scss rules in your config?

**Comment by riddla** [comment]
@shannonmoeller, thanks for the heads up. My configuration is as follows:

```
npm ls stylelint-config-prettier | grep stylelint-config-prettier@
└── stylelint-config-prettier@9.0.3

npm ls stylelint --depth=0 | grep stylelint@
└── stylelint@14.1.0
```

.stylelint-config.js
```
module.exports = {
  extends: [
    'stylelint-config-recommended-scss',
    'stylelint-config-recommended-vue',
    'stylelint-config-prettier',
  ],
}
```

```
npx stylelint assets/scss/_mixins.scss

assets/scss/_mixins.scss
  8:87  ✖  Expected single space before "*"  scss/operator-no-unspaced     
  8:87  ✖  Expected single space after "*"   scss/operator-no-unspaced     
 18:77  ✖  Unexpected newline after "*"      scss/operator-no-newline-after
 26:77  ✖  Unexpected newline after "*"      scss/operator-no-newline-after
 36:77  ✖  Unexpected newline after "*"      scss/operator-no-newline-after
```

Am I missing something?

**Comment by chalkygames123** [comment]
You are seeing lint errors, not "Unknown rule" errors (so this issue has surely been fixed). SCSS rules have been temporarily removed in v9.0.2, so you should turn off the rules by yourself if you want to suppress the errors.

**Comment by chalkygames123** [comment]
@shannonmoeller BTW, I'm trying to resolve the "Unknown rule" issue using the new `overrides` property of Stylelint v14. Would you be willing to receive a PR?

**Comment by riddla** [comment]
@chalkygames123, sorry, I misread this issue.

But @shannonmoeller, can you speak to why these rules were removed (temporarily) and when they will be included again?

**Comment by shannonmoeller** [comment]
@chalkygames123 Feel free to start a new issue regarding the overrides!

@riddla As the OP states, the rules were disabled because they only work when using the scss plugin and many people don’t. We either need to detect whether the plugin is enabled, or create a new stylelint-config-prettier-scss project. I’m leaning towards the new separate project.

**Comment by shannonmoeller** [comment]
Just created a pre-release of https://github.com/prettier/stylelint-config-prettier-scss. Would love some beta testers and rule recommendations. (See https://github.com/prettier/stylelint-config-prettier-scss/issues/1).
