### ISSUE TITLE
CLI helper tool `stylelint-config-prettier` is broken.

### ISSUE THREAD

**Issue by GilShoshan94** [prettier/stylelint-config-prettier#134]
Hi,

As far as I know, extending Stylelint with "stylelint-config-prettier" seems to work fine.

I was curious about the CLI helper tool `stylelint-config-prettier` and what it would report to me.

It fails with:
`TypeError: stylelint.createLinter(...).getConfigForFile is not a function`

After checking a bit what it is about, it seems that this is an internal function of Stylelint and it got modify here: https://github.com/stylelint/stylelint/pull/6415

This should be either fix or simply remove this CLI tool if it is not necessary.
Have a nice day.

**Comment by shannonmoeller** [comment]
Thanks for the report. I'll take a look.

**Comment by shannonmoeller** [comment]
Released as v9.0.4.
