### ISSUE TITLE
Support for stylelint 15 and above

### ISSUE THREAD

**Issue by ghost** [prettier/stylelint-config-prettier#141]
The current version of stylelint is 15.2.0, but peerDependencies are set to a version of stylelint less than 15, so an environment with a version of stylelint 15 or later will cause an error when installing.

https://github.com/prettier/stylelint-config-prettier/blob/master/package.json#L30

If there is no particular reason, it seems better to fix it.

**Comment by shannonmoeller** [comment]
Yep! It’s on purpose. Please see #140.

**Comment by ghost** [comment]
@shannonmoeller 
Sorry、I missed it, thanks
