### ISSUE TITLE
Box shadow indentation bug

### ISSUE THREAD

**Issue by guylando** [prettier/stylelint-config-prettier#21]
Using vscode with latest prettify and stylelint extensions.
The following scss code:
`box-shadow: 0 0 1px 0 $border-color inset, 0 0 1px 0 $border-color, 0 0 1px 0 $border-color;`
Is refactored using prettify to:
```
box-shadow:
    0 0 1px 0 $border-color inset,
 0 0 1px 0 $border-color,
    0 0 1px 0 $border-color;
```
Which makes stylelint complain with the next message:
`Expected indentation of 4 spaces (indentation)`
Manually modifying the code  to be:
```
box-shadow:
    0 0 1px 0 $border-color inset,
    0 0 1px 0 $border-color,
    0 0 1px 0 $border-color;
```
Makes prettify to change it back to:
```
box-shadow:
    0 0 1px 0 $border-color inset,
 0 0 1px 0 $border-color,
    0 0 1px 0 $border-color;
```

**Comment by krishnaPC** [comment]
+1 any solution on this?

**Comment by guylando** [comment]
@krishnaPC for now added /* prettier-ignore */ before that code

**Comment by shannonmoeller** [comment]
The `indentation` rule is the first rule disabled by `stylelint-config-prettier`.

https://github.com/prettier/stylelint-config-prettier/blob/master/src/index.js#L5

I'm guessing you may have an issue with your stylelint configuration or that this is a bug in another tool. Would you mind posting your stylelint config here?

**Comment by guylando** [comment]
@shannonmoeller basically something like:
`extends: ['stylelint-config-standard', 'stylelint-config-recommended-scss']`

**Comment by guylando** [comment]
seems adding stylelint-config-prettier fixes this

**Comment by shannonmoeller** [comment]
@guylando Yep! Exactly.
