### ISSUE TITLE
Specify semver policy

### ISSUE THREAD

**Issue by ThomasdenH** [prettier/stylelint-config-prettier#23]
What semver policy does this package have? Presumably it uses something similar to the [eslint rules](https://github.com/eslint/eslint#semantic-versioning-policy), so usage of a `~` might be recommended.

**Comment by shannonmoeller** [comment]
I do my best to follow [semver](https://semver.org/), yes: breaking.feature.bugfix

**Comment by ThomasdenH** [comment]
Well, eslint can add new lints, meaning breaking a build, in minor versions. Do you mean that this repository will only break builds in major versions?

**Comment by shannonmoeller** [comment]
That's the intent, yes.

**Comment by ThomasdenH** [comment]
Ok, thanks!
