### ISSUE TITLE
Upgrade stylelint-config-prettier peerDependency to stylelint 12.0.0

### ISSUE THREAD

**Issue by the-ult** [prettier/stylelint-config-prettier#45]
stylelint-config-prettier is not compatible with stylelint 12.*
```
stylelint-config-prettier@6.0.0 requires a peer of stylelint@^9.1.1 || ^10.0.0 || ^11.0.0 but none is installed.
```

@see https://github.com/prettier/stylelint-config-prettier/pull/37

**Comment by shannonmoeller** [comment]
Published as v7

**Comment by lensbart** [comment]
Hello! Thanks for your work. Perhaps this change could be described for easier discoverability on the releases page? https://github.com/prettier/stylelint-config-prettier/releases/tag/v7.0.0

Thanks!

**Comment by shannonmoeller** [comment]
Sure. Done.
