### ISSUE TITLE
stylelint: Undefined rule unicode-bom

### ISSUE THREAD

**Issue by yoyo837** [prettier/stylelint-config-prettier#49]
`"stylelint-config-prettier": "^8.0.0"`

**Comment by shannonmoeller** [comment]
The addition of the `unicode-bom` rule was a breaking change and requires `stylelint` >= 11.

https://github.com/prettier/stylelint-config-prettier/releases/tag/v8.0.0

**Comment by yoyo837** [comment]
Thanks reply, all stylelint vscode extensions have not upgraded dependencies > 11 at the moment.

**Comment by shannonmoeller** [comment]
Ok! You’ll want to use v7 of this module until those are updated then.
